version: '5.0'

actions:
  # Zostavax primary analysis based around threshold date of 2013-09-01
  generate_dataset_zostavax_main:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_zostavax.py 
      --output output/zostavax/dataset_zostavax_main.arrow
      --dummy-data-file analysis/dummy_data/dummy_dataset_zostavax.arrow
      --
      --threshold_date "2013-09-01"
    outputs:
      highly_sensitive:
        dataset: output/zostavax/dataset_zostavax_main.arrow

  # Zostavax sensitivity analysis with threshold 3 years earlier
  generate_dataset_zostavax_sens_1:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_zostavax.py 
      --output output/zostavax/dataset_zostavax_sens_1.csv.gz
      --
      --threshold_date "2010-09-01"
    outputs:
      highly_sensitive:
        dataset: output/zostavax/dataset_zostavax_sens_1.csv.gz

  # Zostavax sensitivity analysis with threshold 3 years later
  generate_dataset_zostavax_sens_2:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_zostavax.py 
      --output output/zostavax/dataset_zostavax_sens_2.csv.gz
      --
      --threshold_date "2016-09-01"
    outputs:
      highly_sensitive:
        dataset: output/zostavax/dataset_zostavax_sens_2.csv.gz

  # Shingrix analysis
  generate_dataset_shingrix_main:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_shingrix.py 
      --output output/shingrix/dataset_shingrix_main.csv.gz
      --
      --threshold_date "2023-09-01"
    outputs:
      highly_sensitive:
        dataset: output/shingrix/dataset_shingrix_main.csv.gz
  