version: '5.0'

actions:
  generate_dataset_zostavax_main:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_zostavax.py 
      --output output/zostavax/dataset_zostavax_main.csv.gz
      --
      --index_date "2013-09-01"
    outputs:
      highly_sensitive:
        dataset: output/zostavax/dataset_zostavax_main.csv.gz

  generate_dataset_zostavax_sens_1:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_zostavax.py 
      --output output/zostavax/dataset_zostavax_sens_1.csv.gz
      --
      --index_date "2010-09-01"
    outputs:
      highly_sensitive:
        dataset: output/zostavax/dataset_zostavax_sens_1.csv.gz

  generate_dataset_zostavax_sens_2:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_zostavax.py 
      --output output/zostavax/dataset_zostavax_sens_2.csv.gz
      --
      --index_date "2016-09-01"
    outputs:
      highly_sensitive:
        dataset: output/zostavax/dataset_zostavax_sens_2.csv.gz